### ISSUE TITLE
Purpose of set_Rp() and set_Q_factor()?

### ISSUE THREAD

**Issue by pkerspe** [Seeed-Studio/Seeed_LDC1612#6]
What is the purpose of setting AC resistance and Q Factor in this library?
The two functions exist and are used in the example, but the values are actually never read in the library, so what is their purpose and can they just be ignored?

```
void LDC1612::set_Rp(u8 channel, float n_kom) {
    resistance[channel] = n_kom;
}

void LDC1612::set_Q_factor(u8 channel, float q) {
    Q_factor[channel] = q;
}
```

For the sake of simplicity and and in general those functions should be removed if they are useless and also the examples should be updated to remove their invocations.
Or is there any "future use" or other part where those values are actually needed?

**Comment by Enobs** [comment]
@pkerspe Actually I have the same concern about those parameters. Did you figure out how those work?

**Comment by pkerspe** [comment]
@Enobs na, I just implemented my own code and reused some parts this lib. This library here just seems outdated/unfinished

**Comment by ackPeng** [comment]
@pkerspe Q is the quality factor of the resonator. RP is the AC parallel resistance of the LC resonator at the operating frequency.Detailed information can be found in the hardware manual.：https://files.seeedstudio.com/wiki/Grove-2-Channel_Inductive_Sensor-LDC1612/res/LDC1612.pdf

**Comment by pkerspe** [comment]
@ackPeng not sure how this answers my question to be honest :-) the values are still useless if they are never used in the library.

**Comment by ackPeng** [comment]
@pkerspe Sorry, I thought you needed to know the meaning of these two parameters. At present, these two functions have not been used yet, which seems a bit redundant.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
